name: 'Test example'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile

      # build to check everything is ok
      - run: yarn build

      # run all the examples
      - run: yarn snapshot

      # check that the examples didn't change
      - run: |
          if [ -z "$(git status --porcelain)" ]; then
            # Working directory clean
            exit 0
          else
            # Uncommitted changes
            git status
            exit 1
          fi
